version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User Id=sa;Password=Admin123!
      - Redis__ConnectionString=redis:6379

  gateway:
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - api
    environment:
      - Ocelot__BaseUrl=http://localhost:5001

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  sqlserver-data:
