version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5073:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=DesafioDB;User Id=sa;Password=Admin123!

  gateway:
    build:
      context: ../APIGateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"  
    depends_on:
      - api
    environment:
      - Ocelot__BaseUrl=http://localhost:5000

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
